### ISSUE TITLE
I cannot see the remote video

### ISSUE THREAD

**Issue by zhuisa** [TheWandererLee/WebRTC-UWP-Sample#1]
Hi! I also follow the tutorial, But I cannot see the remote video. Do you know about something? I changed "HttpServerAddress"  into public address.

**Comment by TheWandererLee** [comment]
Unfortunately, I also did not see the remote video when I finished this tutorial. For the project I used this for, it was only important to have the data channels at this time. Also, we quickly moved from [node-dss](https://github.com/bengreenier/node-dss) to [libdatachannel](https://github.com/paullouisageneau/libdatachannel), which I haven't yet uploaded the new version of UWP for that, but the video portion is stripped entirely from that.

Sorry, hopefully you are able to get it working soon. If my other project does use video successfully then I might be able to come back and update this project, but it probably won't be for awhile.

**Comment by zhuisa** [comment]
greeting！Thank your reply. I am very happy to know about other SDK.  Does libdatachannel support audio video communication in HoloLens 2 ？

**Comment by TheWandererLee** [comment]
Yes, it supports a lot of protocols. Node-dss is not really a production
ready signaling server, but libdatachannel does provide some more complete
examples for signaling server and clients. Check it out maybe you can get
their demo clients to work with video. It's a bit harder though their code
is mostly C++ with signaling server examples in Rust/Node/or Python

**Comment by zhuisa** [comment]
Thanks for your reply! Maybe I should try it. Good Luck!

**Comment by zhuisa** [comment]
Thanks, you help me  a lot. I close the issue.

**Comment by TheWandererLee** [comment]
Were you able to fix it? What was your conclusion?

**Comment by zhuisa** [comment]
Hi！I don't fix it. I'm going to try to use libdatachannel, because it also stream a video to another.
